!!com.snobot.simulator.config.SimulatorConfig
mAccelerometers:
- mHandle: 212
  mName: SPI NavX X Accel
- mHandle: 213
  mName: SPI NavX Y Accel
- mHandle: 214
  mName: SPI NavX Z Accel
mAnalogIO:
- mHandle: 0
  mName: Analog 0
- mHandle: 2
  mName: Analog 2
- mHandle: 3
  mName: Analog 3
mDefaultI2CWrappers:
  0: None
  1: None
mDefaultSpiWrappers:
  0: null
  1: null
  2: null
  3: null
  4: NavX
mDigitalIO: []
mEncoders: []
mGyros:
- mHandle: 212
  mName: SPI NavX Yaw
- mHandle: 213
  mName: SPI NavX Pitch
- mHandle: 214
  mName: SPI NavX Roll
mPwm:
- mHandle: 103
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: 'CAN SC: 3'
- mHandle: 104
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: 'CAN SC: 4'
- mHandle: 105
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: 'CAN SC: 5'
- mHandle: 108
  mMotorModelConfig: null
  mMotorSimConfig: null
  mName: 'CAN SC: 8'
mRelays: []
mSimulatorComponents: []
mSolenoids:
- mHandle: 0
  mName: Solenoid 0
- mHandle: 1
  mName: Solenoid 1
